// Generated by CoffeeScript 2.3.2
// all.coffee: list all draws (complete)

var https, utils, vue;

utils = require('../js/utils.js');

https = require('https');

vue = new Vue({
  el: '#app',
  data: {
    draws: []
  },
  filters: {
    number: function(v) {
      if ((v != null) && typeof v.toLocaleString === 'function') {
        return v.toLocaleString();
      } else {
        return '';
      }
    },
    toYMD: utils.toYMD,
    toDMY: utils.toDMY
  },
  methods: {
    getFirstDraws: function() {
      return https.get(utils.qstring('SELECT * LIMIT 25'), (res) => {
        var body;
        body = '';
        res.setEncoding('utf-8');
        res.on('data', function(d) {
          return body += d;
        });
        res.on('error', function(e) {
          return console.log(`query error: ${e}`);
        });
        return res.on('end', () => {
          var json;
          json = utils.parseResponse(body.toString());
          return this.draws = utils.qresult(json);
        });
      });
    }
  },
  created: function() {
    this.getFirstDraws();
    return window.onscroll = function() {
      console.log('onscroll called');
      if (document.documentElement.scrollTop + window.innerHeight === document.documentElement.offsetHeight) {
        return console.log('reached bottom of window');
      }
    };
  }
});
