// Generated by CoffeeScript 1.10.0
var https, utils, vue;

utils = require('../js/utils.js');

https = require('https');

vue = new Vue({
  el: '#app',
  filters: {
    number: function(v) {
      if ((v != null) && typeof v.toLocaleString === 'function') {
        return v.toLocaleString();
      } else {
        return '';
      }
    },
    toYMD: utils.toYMD,
    toDMY: utils.toDMY
  },
  methods: {
    getLastDraw: function() {
      var q;
      q = 'SELECT A, B\nORDER BY B DESC\nLIMIT 1\nLABEL A \'number\', B \'date\'';
      return https.get(utils.qstring(q), (function(_this) {
        return function(res) {
          var body;
          body = '';
          res.setEncoding('utf-8');
          res.on('data', function(d) {
            return body += d;
          });
          res.on('error', function(e) {
            return console.log("query error: " + e);
          });
          return res.on('end', function() {
            var json;
            json = utils.parseResponse(body.toString());
            return _this.lastDraw = (utils.qresult(json))[0];
          });
        };
      })(this));
    },
    getTotalDraws: function() {
      var q;
      q = 'SELECT COUNT(A)\nLABEL COUNT(A) \'count\'';
      return https.get(utils.qstring(q), (function(_this) {
        return function(res) {
          var body;
          body = '';
          res.setEncoding('utf-8');
          res.on('data', function(d) {
            return body += d;
          });
          res.on('error', function(e) {
            return console.log("query error: " + e);
          });
          return res.on('end', function() {
            var json;
            json = utils.parseResponse(body);
            return _this.count = (utils.qresult(json))[0].count;
          });
        };
      })(this));
    },
    getFreq: function() {
      var i, j, jq, lfreq, lq;
      lfreq = [];
      for (i = j = 0; j <= 34; i = ++j) {
        lfreq.push([0, 0, 0, 0, 0, 0, 0, 0]);
      }
      lq = 'SELECT X, Y, Z, AA, AB, AC, AD, AE\n:filter';
      lq = (function() {
        switch (this.drum) {
          case utils.VENUS:
            return lq.replace(/\:filter/, "WHERE B <= date '" + (utils.toYMD(utils.VENUS_DATE)) + "'");
          case utils.STRESA:
            return lq.replace(/\:filter/, "WHERE B >= date '" + (utils.toYMD(utils.STRESA_DATE)) + "'");
          default:
            return lq.replace(/\:filter/, '');
        }
      }).call(this);
      https.get(utils.qstring(lq), (function(_this) {
        return function(res) {
          var body;
          body = '';
          res.setEncoding('utf-8');
          res.on('data', function(d) {
            return body += d;
          });
          res.on('error', function(e) {
            return console.log("query error: " + e);
          });
          res.on('end', function() {
            var json, k, len, r, recs;
            json = utils.parseResponse(body);
            recs = utils.qresult(json);
            for (k = 0, len = recs.length; k < len; k++) {
              r = recs[k];
              lfreq[r.lwc1][0] += 1;
              lfreq[r.lwc2][1] += 1;
              lfreq[r.lwc3][2] += 1;
              lfreq[r.lwc4][3] += 1;
              lfreq[r.lwc5][4] += 1;
              lfreq[r.lwc6][5] += 1;
              lfreq[r.lwc7][6] += 1;
              lfreq[r.lwcp][7] += 1;
            }
            return _this.lfreq = lfreq;
          });
          return null;
        };
      })(this));
      jq = 'SELECT BE\n:filter';
      jq = (function() {
        switch (this.drum) {
          case utils.VENUS:
            return jq.replace(/\:filter/, "WHERE B <= date '" + (utils.toYMD(utils.VENUS_DATE)) + "'");
          case utils.STRESA:
            return jq.replace(/\:filter/, "WHERE B >= date '" + (utils.toYMD(utils.STRESA_DATE)) + "'");
          default:
            return jq.replace(/\:filter/, '');
        }
      }).call(this);
      https.get(utils.qstring(jq), (function(_this) {
        return function(res) {
          var body, jfreq, k;
          jfreq = [];
          for (i = k = 0; k <= 9; i = ++k) {
            jfreq.push([0, 0, 0, 0, 0, 0]);
          }
          body = '';
          res.setEncoding('utf-8');
          res.on('data', function(d) {
            return body += d;
          });
          res.on('error', function(e) {
            return console.log("query error: " + e);
          });
          res.on('end', function() {
            var a, arr, json, l, len, n, recs;
            json = utils.parseResponse(body);
            recs = utils.qresult(json);
            arr = recs.map(function(r) {
              return r.jwc.split('').map(function(e) {
                return parseInt(e);
              });
            });
            for (l = 0, len = arr.length; l < len; l++) {
              a = arr[l];
              for (i in a) {
                n = a[i];
                jfreq[n][i]++;
              }
            }
            return _this.jfreq = jfreq;
          });
          return null;
        };
      })(this));
      return null;
    },
    drumChanged: function() {
      console.log("Drum is:", this.drum);
      return this.getFreq();
    }
  },
  data: {
    count: null,
    lastDraw: {},
    lfreq: [],
    jfreq: [],
    drum: 'BOTH'
  },
  created: function() {
    console.log(utils.VENUS_DATE, utils.toYMD(utils.VENUS_DATE));
    console.log(utils.STRESA_DATE, utils.toYMD(utils.STRESA_DATE));
    this.getTotalDraws();
    this.getLastDraw();
    return this.getFreq();
  }
});
