// Generated by CoffeeScript 1.10.0
var https, utils, vue;

utils = require('../js/utils.js');

https = require('https');

vue = new Vue({
  el: '#app',
  data: {
    draws: []
  },
  filters: {
    number: function(v) {
      if ((v != null) && typeof v.toLocaleString === 'function') {
        return v.toLocaleString();
      } else {
        return '';
      }
    },
    toYMD: utils.toYMD,
    toDMY: utils.toDMY
  },
  methods: {
    getDraws: function() {
      var q;
      q = 'SELECT\n  A, B,\n  C, X, Y, Z, AA, AB, AC, AD, AE,\n  AF, BE\nORDER BY B DESC\nLIMIT 25';
      return https.get(utils.qstring(q), (function(_this) {
        return function(res) {
          var body;
          body = '';
          res.setEncoding('utf-8');
          res.on('data', function(d) {
            return body += d;
          });
          res.on('error', function(e) {
            return console.log("query error: " + e);
          });
          return res.on('end', function() {
            var json;
            json = utils.parseResponse(body.toString());
            return _this.draws = utils.qresult(json);
          });
        };
      })(this));
    }
  },
  created: function() {
    this.getDraws();
    return console.log(location.pathname);
  }
});
