// Generated by CoffeeScript 2.3.2
// main.coffee

var BrowserWindow, Menu, app, createWindow, debugging, dialog, electron, icon, nativeImage, path, url, win;

electron = require('electron');

path = require('path');

url = require('url');

({app, BrowserWindow, Menu, dialog, nativeImage} = electron);

// main window
// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is garbage collected.
win = null;

icon = nativeImage.createFromPath(path.join(__dirname, './img/air-e.png'));

debugging = true;

createWindow = function() {
  var menu, mnutmpl;
  win = new BrowserWindow({
    width: 1000,
    height: 600,
    title: 'Lotto',
    background: '#002b36'
  });
  //            icon: './img/lotto-e.png'
  win.loadFile('./views/home.html');
  win.maximize();
  win.webContents.openDevTools();
  console.log(process.argv);
  // build menu
  mnutmpl = [
    {
      label: 'Stats',
      submenu: [
        {
          label: 'Stats Lotto and Joker: sales and winners',
          click: function() {
            return win.loadFile('./views/stats.html');
          }
        },
        {
          type: 'separator'
        },
        {
          label: 'Drawn numbers'
        }
      ]
    },
    {
      label: 'View',
      submenu: [
        {
          label: '1st category winners',
          click: function() {
            return win.loadFile('./views/cat1.html');
          }
        },
        {
          type: 'separator'
        },
        {
          label: '2nd category winners',
          click: function() {
            return win.loadFile('./views/cat2.html');
          }
        }
      ]
    },
    {
      label: 'Help',
      submenu: [
        {
          label: 'About',
          click: function() {
            return dialog.showMessageBox(win,
        {
              type: 'info',
              title: 'About',
              message: 'About message...',
              detail: 'Details here...',
              buttons: ['ok']
            },
        //       icon: icon
        //       icon: electron.nativeImage.createFromPath path.join __dirname, '../img/air-e.png'
        //       icon: path.join __dirname, '../img/air-e.png'
        function(btn,
        chk) {
              return console.log(btn,
        chk);
            });
          }
        },
        {
          label: 'Debugging',
          accelerator: 'Ctrl+Shift+I',
          type: 'checkbox',
          checked: debugging,
          role: 'toggledevtools',
          click: function() {
            debugging = !debugging;
            return win.webContents.toggleDevTools();
          }
        }
      ]
    },
    {
      label: 'Quit',
      accelerator: 'Ctrl+Q',
      click: function() {
        return app.quit();
      }
    }
  ];
  menu = Menu.buildFromTemplate(mnutmpl);
  Menu.setApplicationMenu(menu);
  // emitted when the window is closed
  // Dereference the window object, usually you would store windows
  // in an array if your app supports multi windows, this is the time
  // when you should delete the corresponding element.
  win.on('closed', function() {
    // close any other windows here
    return win = null;
  });
  // return val from createWindow()
  return null;
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', function() {
  return createWindow();
});

// process command arguments via process.argv

// create other windows here

// On macOS it's common to re-create a window in the app when the
// dock icon is clicked and there are no other windows open.
app.on('activate', function() {
  if (win === null) {
    return createWindow();
  }
});

// Quit when all windows are closed.
// On macOS it is common for applications and their menu bar
// to stay active until the user quits explicitly with Cmd + Q
app.on('window-all-closed', function() {
  if (process.platform !== 'darwin') {
    return app.quit();
  }
});

// TODO:
// - create local module utils accessible for all views etc.
// - first page: last draws...
