// Generated by CoffeeScript 1.10.0
var BrowserWindow, Menu, app, createWindow, debugging, dialog, electron, icon, nativeImage, path, url, win;

electron = require('electron');

path = require('path');

url = require('url');

app = electron.app, BrowserWindow = electron.BrowserWindow, Menu = electron.Menu, dialog = electron.dialog, nativeImage = electron.nativeImage;

win = null;

icon = nativeImage.createFromPath(path.join(__dirname, './img/air-e.png'));

debugging = true;

createWindow = function() {
  var menu, mnutmpl;
  win = new BrowserWindow({
    width: 1000,
    height: 600,
    title: 'Lotto',
    background: '#002b36'
  });
  win.loadFile('./views/home.html');
  win.maximize();
  win.webContents.openDevTools();
  console.log(process.argv);
  mnutmpl = [
    {
      label: 'Stats',
      submenu: [
        {
          label: 'Stats Lotto and Joker: sales and winners',
          click: function() {
            return win.loadFile('./views/stats.html');
          }
        }, {
          type: 'separator'
        }, {
          label: 'Drawn numbers'
        }
      ]
    }, {
      label: 'View',
      submenu: [
        {
          label: '1st category winners',
          click: function() {
            return win.loadFile('./views/cat1.html');
          }
        }, {
          type: 'separator'
        }, {
          label: '2nd category winners',
          click: function() {
            return win.loadFile('./views/cat2.html');
          }
        }
      ]
    }, {
      label: 'Help',
      submenu: [
        {
          label: 'About',
          click: function() {
            return dialog.showMessageBox(win, {
              type: 'info',
              title: 'About',
              message: 'About message...',
              detail: 'Details here...',
              buttons: ['ok']
            }, function(btn, chk) {
              return console.log(btn, chk);
            });
          }
        }, {
          label: 'Debugging',
          accelerator: 'Ctrl+Shift+I',
          type: 'checkbox',
          checked: debugging,
          role: 'toggledevtools',
          click: function() {
            debugging = !debugging;
            return win.webContents.toggleDevTools();
          }
        }
      ]
    }, {
      label: 'Quit',
      accelerator: 'Ctrl+Q',
      click: function() {
        return app.quit();
      }
    }
  ];
  menu = Menu.buildFromTemplate(mnutmpl);
  Menu.setApplicationMenu(menu);
  win.on('closed', function() {
    return win = null;
  });
  return null;
};

app.on('ready', function() {
  return createWindow();
});

app.on('activate', function() {
  if (win === null) {
    return createWindow();
  }
});

app.on('window-all-closed', function() {
  if (process.platform !== 'darwin') {
    return app.quit();
  }
});
