// Generated by CoffeeScript 2.3.2
// utils.coffee
// Handles google script/sheets

var D20DATE, D20DRAW, D20YEAR, GS_KEY, GS_URL, STRESA, STRESA_DATE, VENUS, VENUS_DATE, parseResponse, qresult, qstring, toDMY, toYMD;

GS_KEY = "1deUDEVwaNPH1fgy3RlmV98TwgVtHfxQc7gA9YeVs_mc";

GS_URL = "https://docs.google.com";

VENUS_DATE = Date.parse("2011-09-15"); // date ≤ 15.09.2011

STRESA_DATE = Date.parse("2011-09-17"); // date ≥ 17.09.2011

D20DATE = Date.parse("2016-09-10"); // date ≥ 10.09.2016; draw = 73

D20DRAW = 73;

D20YEAR = 2016;

VENUS = 'VENUS';

STRESA = 'STRESA';

qstring = function(qry) {
  return `${GS_URL}/spreadsheets/d/${GS_KEY}/gviz/tq?tqx=out:json&tq=${encodeURI(qry)}`;
};

parseResponse = function(r) {
  return JSON.parse(r.replace(/(^.+?\()|(^\/.*\/$)|\);$/mg, ''));
};

qresult = function(json) {
  var c, h, i, j, k, len, len1, r, ref, ref1, rset;
  rset = [];
  ref = json.table.rows;
  for (j = 0, len = ref.length; j < len; j++) {
    r = ref[j];
    h = {};
    ref1 = json.table.cols;
    for (i = k = 0, len1 = ref1.length; k < len1; i = ++k) {
      c = ref1[i];
      h[c.label] = r.c[i].v;
      if (c.type === 'date') {
        h[c.label] = eval('new ' + h[c.label]);
      }
    }
    rset.push(h);
  }
  return rset;
};

// default separator is '-'
toYMD = function(d) {
  var sep;
  if (!d) {
    return null;
  }
  if (!(d instanceof Date)) {
    d = new Date(Date.parse(d));
  }
  sep = arguments.length > 1 ? arguments[1] : '-';
  return (new Date(d - d.getTimezoneOffset() * 1000 * 60)).toISOString().slice(0, 10).split('-').join(sep);
};

// default separator is '.'
toDMY = function(d) {
  var sep;
  if (!d) {
    return null;
  }
  if (!(d instanceof Date)) {
    d = new Date(Date.parse(d));
  }
  sep = arguments.length > 1 ? arguments[1] : '.';
  return (new Date(d - d.getTimezoneOffset() * 1000 * 60)).toISOString().slice(0, 10).split('-').reverse().join(sep);
};

module.exports.GS_KEY = GS_KEY;

module.exports.GS_URL = GS_URL;

module.exports.VENUS_DATE = VENUS_DATE;

module.exports.STRESA_DATE = STRESA_DATE;

module.exports.D20DATE = D20DATE;

module.exports.D20DRAW = D20DRAW;

module.exports.D20YEAR = D20YEAR;

module.exports.VENUS = VENUS;

module.exports.STRESA = STRESA;

module.exports.qstring = qstring;

module.exports.parseResponse = parseResponse;

module.exports.qresult = qresult;

module.exports.toYMD = toYMD;

module.exports.toDMY = toDMY;
